### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Vad-ast** [utianayuba/mitaka-trusty#1]
On controller node after command
su -s /bin/sh -c "keystone-manage db_sync" keystone
get
14666 WARNING oslo_db.sqlalchemy.engines [-] SQL connection failed. 10 attempts left.

**Comment by utianayuba** [comment]
please make sure your mariadb service is running without error.
# service mysql status
test root login to mysql prompt
# mysql -u root -p
Password: RAHASIA

**Comment by Vad-ast** [comment]
**$ sudo service mysql status**
root@controller:/home/user# service mysql status
● mysql.service - LSB: Start and stop the mysql database server daemon
   Loaded: loaded (/etc/init.d/mysql; bad; vendor preset: enabled)
   Active: active (running) since Wed 2016-06-15 06:13:07 EDT; 5h 2min ago
     Docs: man:systemd-sysv-generator(8)
    Tasks: 27
   Memory: 85.1M
      CPU: 6.335s
   CGroup: /system.slice/mysql.service
           ├─3669 /bin/bash /usr/bin/mysqld_safe
           ├─3670 logger -p daemon err -t /etc/init.d/mysql -i
           ├─3829 /usr/sbin/mysqld --basedir=/usr --datadir=/var/lib/mysql --plugin-dir=/usr/lib/mysql/plugin --user=mysql --skip-log-error --pid-file=/var/run/mysqld/mysqld.pid --socket=/v
           └─3830 logger -t mysqld -p daemon error

Jun 15 06:13:06 controller mysqld[3830]: 160615  6:13:06 [Note] InnoDB: 128 rollback segment(s) are active.
Jun 15 06:13:06 controller mysqld[3830]: 160615  6:13:06 [Note] InnoDB: Waiting for purge to start
Jun 15 06:13:06 controller mysqld[3830]: 160615  6:13:06 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.29-76.2 started; log sequence number 1616727
Jun 15 06:13:06 controller mysqld[3830]: 160615  6:13:06 [Note] Plugin 'FEEDBACK' is disabled.
Jun 15 06:13:06 controller mysqld[3830]: 160615  6:13:06 [Note] Server socket created on IP: '127.0.0.1'.
Jun 15 06:13:06 controller mysqld[3830]: 160615  6:13:06 [Note] /usr/sbin/mysqld: ready for connections.
Jun 15 06:13:06 controller mysqld[3830]: Version: '10.0.25-MariaDB-0ubuntu0.16.04.1'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  Ubuntu 16.04
Jun 15 06:13:07 controller mysql[3639]:    ...done.
Jun 15 06:13:07 controller systemd[1]: Started LSB: Start and stop the mysql database server daemon.
Jun 15 06:13:42 controller mysqld[3830]: 160615  6:13:42 [Warning] 'user' entry 'root@localhost' has both a password and an authentication plugin specified. The password will be ignored.
lines 1-23/23 (END)


**root@controller:/home/user# sudo mysql -u root -p**
Enter password:
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 40
Server version: 10.0.25-MariaDB-0ubuntu0.16.04.1 Ubuntu 16.04

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> show databases;
+--------------------+
| Database           |
+--------------------+
| information_schema |
| keystone           |
| mysql              |
| performance_schema |
+--------------------+
4 rows in set (0.00 sec)

MariaDB [(none)]> use keystone
Database changed
MariaDB [keystone]> show tables;
Empty set (0.00 sec)

MariaDB [keystone]>



DB is empty.

**Comment by utianayuba** [comment]
Try mysql -h controller -u keystone -pRAHASIA.
At beginning the database is empty, db_sync command will populate the database.
If the warning message still appear, try to ignore it and move forward to "Service Entity & API Endpoints" steps and see what happen.
